### ISSUE TITLE
 AbdomenMRUS-prostate-segmentation

### ISSUE THREAD

**Issue by jakubMitura14** [DIAGNijmegen/picai_prep#24]
First, thank you for publishing your work !!
I cross reference from https://github.com/DIAGNijmegen/AbdomenMRUS-prostate-segmentation/issues/2

I am trying to execute your algorithm on a private dataset.
I had mha files and preprocessed them to nnU-Net Raw Data Archive
using settings
```
mha2nnunet_settings = {
    "dataset_json": {
        "task": "Task2202_prostate_segmentation",
        "description": "bpMRI scans from PI-CAI dataset to train nnUNet baseline",
        "tensorImageSize": "4D",
        "reference": "",
        "licence": "",
        "release": "1.0",
        "modality": {
            "0": "T2W",
            "1": "CT",
            "2": "HBV"
        },
        "labels": {
            "0": "background",
            "1": "lesion"
        }
    },
    "preprocessing": {
        "spacing": [
            3.0,
            0.5,
            0.5
        ],
    },
    "archive": arr
}

```
where arr is a list  with supplied metadata and file list with relative paths to input folder
```
{"patient_id": tupl["patient_id"],
                "study_id":  tupl["study_id"],
                "scan_paths": newFileList, 
                "annotation_path": tupl["patient_id"]+'.nii.gz'
                }
```
after preprocessing I have files like

![image](https://user-images.githubusercontent.com/53857487/187936669-5c4c4200-e285-4b4a-b6f1-8a6b89c8656d.png)

Then I try to run docker by
```
docker run --gpus='"device=0"' \
    -v /workspaces/baselineUnet/newOutput/Task2202_prostate_segmentation:/workdir/nnUNet_raw_data \
    -v /workspaces/baselineUnet/results:/workdir/results \
    joeranbosma/picai_nnunet:latest nnunet plan_train \
    Task2202_prostate_segmentation /workdir/ \
    --trainer nnUNetTrainerV2_Loss_FL_and_CE_checkpoints --fold 0
```
I get error 
```
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/home/user/nnunet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 103, in main
    task_name = convert_id_to_task_name(i)
  File "/home/user/nnunet/nnunet/utilities/task_name_id_conversion.py", line 51, in convert_id_to_task_name
    raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 2202. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/user/data
RESULTS_FOLDER=/workdir/results
nnUNet_raw_data_base=/workdir



[#] Creating plans and preprocessing data
Traceback (most recent call last):
  File "/usr/local/bin/nnunet", line 568, in <module>
    action(argv)
  File "/usr/local/bin/nnunet", line 250, in plan_train
    subprocess.check_call(cmd)
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nnUNet_plan_and_preprocess', '-t', '2202', '-tl', '1', '-tf', '1', '--verify_dataset_integrity', '--planner2d', 'None']' returned non-zero exit status 1.
...

Traceback (most recent call last):
  File "/usr/local/bin/nnunet", line 568, in <module>
    action(argv)
  File "/usr/local/bin/nnunet", line 250, in plan_train
    subprocess.check_call(cmd)
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nnUNet_plan_and_preprocess', '-t', '2202', '-tl', '1', '-tf', '1', '--verify_dataset_integrity', '--planner2d', 'None']' returned non-zero exit status 1.
```
Files as far as I manually inspected portion using slicer are not corrupted.

part of preprocessing log information 
```
CASE 017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099
	PATIENT ID	017
	STUDY ID	1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099

Importing 3 scanss
	+ (1) /workspaces/baselineUnet/mhaArchive/017/1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_t2w.mha
	+ (2) /workspaces/baselineUnet/mhaArchive/017/1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_adc.mha
	+ (3) /workspaces/baselineUnet/mhaArchive/017/1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_hbv.mha
Importing annotation
	+ /workspaces/baselineUnet/labels/017.nii.gz
Writing 3 scans including annotation
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0000.nii.gz
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0001.nii.gz
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0002.nii.gz
Wrote annotation to /workspaces/baselineUnet/newOutput/taskA/labelsTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099.nii.gz
Importing 3 scanss
	+ (4) /workspaces/baselineUnet/mhaArchive/017/1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_t2w.mha
	+ (5) /workspaces/baselineUnet/mhaArchive/017/1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_adc.mha
	+ (6) /workspaces/baselineUnet/mhaArchive/017/1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_hbv.mha
Importing annotation
	+ /workspaces/baselineUnet/labels/017.nii.gz
Writing 6 scans including annotation
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0000.nii.gz
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0001.nii.gz
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0002.nii.gz
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0003.nii.gz
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0004.nii.gz
Wrote image to /workspaces/baselineUnet/newOutput/taskA/imagesTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099_0005.nii.gz
Wrote annotation to /workspaces/baselineUnet/newOutput/taskA/labelsTr/017_1.3.12.2.1107.5.8.15.100960.30000022021714463775000001099.nii.gz
========================================================================================================================
CASE 234_1.3.12.2.1107.5.2.41.69644.30000020011405272273800000001
	PATIENT ID	234
	STUDY ID	1.3.12.2.1107.5.2.41.69644.30000020011405272273800000001
```

**Comment by joeranbosma** [comment]
Hi Jakub,

Apologies for my delay in responding to your other thread, thanks for reminding me again!
I will answer shortly on the other thread (https://github.com/DIAGNijmegen/AbdomenMRUS-prostate-segmentation/issues/2), I think that's a bit easier for others to find.

Kind regards,
Joeran
